export const BASE_URL = "http://localhost:8080"
export const POST_SAVE_URL = "/api/add-post"
export const SEARCH_USER = "/api/search-user/?email="
export const CREATE_USER = "/api/create-user"
export const USER_HAVE_ALL_POST_GET = "/api/user-all-article?email="